server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: product_api
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: validate   # create | update | validate | none
    show-sql: true